[package]
name = "ozzypig/fisticuffs-2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@3.1.1"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.2"
Cmdr = "evaera/cmdr@1.12.0"
