[package]
name = "ozzypig/fisticuffs-2"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
t = "osyrisrblx/t@3.1.1"
Logging = "ozzypig/logging@0.3.0"
Promise = "howmanysmall/typed-promise@4.0.6"
Comm = "sleitnick/comm@1.0.1"
Signal = "sleitnick/signal@2.0.3"
Component = "sleitnick/component@2.4.8"
Trove = "sleitnick/trove@1.8.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.2"
Cmdr = "evaera/cmdr@1.12.0"
